### ISSUE TITLE
Longview api

### ISSUE THREAD

**Issue by bonesoul** [linode/longview#13]
Any plans for longview api?

**Comment by meshy** [comment]
:+1: It'd be really nice to be able to get the API token from an API to remove this manual step from our automated deployment.

**Comment by nicolasdanelon** [comment]
:+1: yes !

**Comment by jasonbronson** [comment]
yes

**Comment by nicolasdanelon** [comment]
@linode ;)

**Comment by displague** [comment]
There are two APIs at play here, the Longview API (lv.linode.com) and the Linode API (api.linode.com).

Longview will not be making an appearance in the Linode v3 API.

However, using the Linode v4 API it is currently possible to create a new Longview Client and get the API and install keys:

- https://developers.linode.com/v4/reference/endpoints/longview/clients#POST

The Longview API itself is not documented, however the endpoints can be easily scraped by watching the Longview Client of the Linode Manager interact with that API, others have created Longview Clients based on this:
- https://github.com/telega/longview-data
- https://manager.linode.com/media/js/longview.js?16 The current manager's Longview client
- [my Longview Client PR against the new manager]( https://github.com/displague/manager/blob/607159d3f0e31d768c20269b18b4ffc837058037/src/api/longview/stats.js)
