### ISSUE TITLE
LWP::Protocol::https is needed for v1.1-5 to run

### ISSUE THREAD

**Issue by halles** [linode/longview#26]
First time I run into this issue. Today I installed longview on a new machine and it wouldn't start logging because of a missing package, related to Perl. I also updated longview on other machines (updated the whole machine) that were running almost since a year ago, and had no issues. Machines are all running CentOS 7 but only the one with the issue was created just a month ago. All three of them were updated at the same time and only the new one presented the issue. I would think it is related with perl dependencies but still the longview installer can take care of this issue.

The missing yum package is `perl-LWP-Protocol-https`. After installing the package everything worked as expected.

Log with errors

`05/06 15:22:24 INFO Longview[3975] - Starting Longview Agent version 1.1.5
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Memory.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/CPU.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Processes.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Network.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Disk.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/SysInfo.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Ports.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/MySQL.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/Nginx.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/Apache.pm
05/06 15:22:24 INFO Longview[3976] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Packages/YUM.pm
05/06 15:22:24 INFO Longview[3976] - Start up complete
05/06 15:22:28 WARN Longview[3976] - Unable to find a location for the Nginx status page, defaulting to http://127.0.0.1/nginx_status
05/06 15:22:28 ERROR Longview[3976] - Unable to access server status page (http://127.0.0.1/nginx_status) for Nginx: 404 Not Found
05/06 15:22:28 INFO Longview[3976] - 501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
05/06 15:22:28 INFO Longview[3976] - LWP will support https URLs if the LWP::Protocol::https module
is installed.
`

Log when running correctly
`05/06 22:28:12 INFO Longview[31993] - Starting Longview Agent version 1.1.5
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Memory.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/CPU.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Processes.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Network.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Disk.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/SysInfo.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Ports.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/MySQL.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/Nginx.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Applications/Apache.pm
05/06 22:28:12 INFO Longview[31994] - Loading module /opt/linode/longview/Linode/Longview/DataGetter/Packages/YUM.pm
05/06 22:28:12 INFO Longview[31994] - Start up complete
05/06 22:28:14 WARN Longview[31994] - Unable to find a location for the Nginx status page, defaulting to http://127.0.0.1/nginx_status`

**Comment by jamesottinger** [comment]
@halles, thank you for taking the time to report this and provide the logs! A new Centos 7 package was published this morning to fix this specific issue. Closing as completed.
