### ISSUE TITLE
Generic installation problem

### ISSUE THREAD

**Issue by amphineko** [linode/longview#27]
I'm trying installing Longview from Linode Manager, which is a way prompts the following message to instruct installation:

```
curl -s https://lv.linode.com/<some identifier> | sudo bash
```

I used this way to get Longview installed on my Gentoo server, and the installation script selected generic_install(), which has something wrong with the code will run when has_git() returns 0.

Then forcing has_git() always returning 1 made the installation succeeded. This problem is still exist at the moment I post this. I can't think of anywhere but here to post this problem.

**Comment by dwfreed** [comment]
Longview doesn't officially support Gentoo, and the generic install leaves things to be desired.  I made ebuilds for Longview in my overlay, 'dwfreed'.  I haven't made a 1.1.5 release yet (but I will get that up shortly), but the 9999 ebuild should work just fine.  The package is called net-analyzer/linode-longview in my overlay.

**Comment by amphineko** [comment]
I think this problem is not specific to Gentoo, but any Linux environment
which will use generic install and has git installed.

在 2016年5月16日週一 上午12:20，Doug Freed <notifications@github.com> 寫道：

> Longview doesn't officially support Gentoo, and the generic install leaves
> things to be desired. I made ebuilds for Longview in my overlay, 'dwfreed'.
> I haven't made a 1.1.5 release yet (but I will get that up shortly), but
> the 9999 ebuild should work just fine. The package is called
> net-analyzer/linode-longview in my overlay.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linode/longview/issues/27#issuecomment-219295234>
>
-- 

Naoki Rinmous
