### ISSUE TITLE
Failed to fetch http://apt-longview.linode.com/dists/trusty/main/binary-amd64/Packages  403  

### ISSUE THREAD

**Issue by 1a57danc3** [linode/longview#32]
W: Failed to fetch http://apt-longview.linode.com/dists/trusty/main/binary-amd64/Packages  403  Forbidden [IP: 112.124.140.210 80]

W: Failed to fetch http://apt-longview.linode.com/dists/trusty/main/binary-i386/Packages  403  Forbidden [IP: 112.124.140.210 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linode-longview

**Comment by displague** [comment]
This URL is currently available.  This was likely a temporary outage.

Thanks for reporting!
