### ISSUE TITLE
CentOS 8 can't install longview, why?

### ISSUE THREAD

**Issue by PoLun-Wang** [linode/longview#45]
Because Linode even didn't prepare for the new version of lonview.

**Figure out the problem:**
I followed the installation instructions, enter this command with root:
`curl -s https://lv.linode.com/xxxxx | sudo bash`
And this is the response I got:
```
Longview Repo                                                                             81  B/s | 233  B     00:02
Error: Failed to synchronize cache for repo 'longview'
```

After then I check the repository file in the path "/etc/yum.repos.d/longview.repo".
```
[longview]
name=Longview Repo
baseurl=https://yum-longview.linode.com/centos/8/noarch/
enabled=1
gpgcheck=1
```
Then I tried to find out the problems. First, check the "baseurl" of the repository.
This is the result that they don't put the link of version 8. [screenshot](https://imgur.com/a/hyoUgxM)

**Try to solve it:**
OK, I thought maybe this old version still works fine in CentOS 8.
I modified the repository file "/etc/yum.repos.d/longview.repo"
```
[longview]
name=Longview Repo
baseurl=https://yum-longview.linode.com/centos/7/noarch/
enabled=1
gpgcheck=1
```

Then I followed the [manual Installation](https://www.linode.com/docs/platform/longview/longview/#manual-installation-with-yum-or-apt) to install longview. These are the error message after I entered `yum install linode-longview`:
```
Last metadata expiration check: 0:16:10 ago on Sat 12 Oct 2019 01:18:35 PM CST.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides perl(Crypt::SSLeay) needed by linode-longview-1.1-5.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Do anyone has experience install longview on CentOS 8? 
Or can anyone point out which step I got wrong?

**Comment by madappally** [comment]
Me too having the same issue

**Comment by PoLun-Wang** [comment]
> Me too having the same issue

And they just keep ignoring this issue.

**Comment by Cartoonman** [comment]
Has this project been abandoned? Seems like many other issues have basically stalled out. I also have this issue and can't use Longview for CentOS 8.

**Comment by rmcintosh** [comment]
Hi all,

Longview has been packaged for CentOS 8. You should be able to install it via the normal methods: https://www.linode.com/docs/platform/longview/what-is-longview/#install-linode-longview
